#!/bin/bash
# install docker on your computer
export pwd=$(pwd)
cd /ldata/reedma/docker_stuff/container-metabolab  # directory containing dockerfile
docker image rm --force imeta_image$1
docker build -t imeta_image$1 .
cd $pwd
docker rm -f imeta_container$1
# path below is path to directory containing your container_script.ml
docker  run  -t -v  /ldata/reedma/docker_stuff/container-metabolab/MTBLS1_small:/mydata -w /mydata --name imeta_container$1 imeta_image$1

